import dotenv from 'dotenv';
dotenv.config();

import mongoose from 'mongoose';
import { connectDB } from '../config/db.js';
import { Category } from '../models/Category.js';
import { Product } from '../models/Product.js';
import { CraftVideo } from '../models/CraftVideo.js';

const SEED_CATEGORIES = [
  {
    slug: 'candles',
    name: 'Candles',
    description: 'Hand-poured artisan candles made with natural soy and beeswax.',
    image: '/images/categories/candles.jpg',
    productCount: 4,
  },
  {
    slug: 'soaps',
    name: 'Soaps',
    description: 'Cold-processed handmade soaps with natural botanicals.',
    image: '/images/categories/soaps.jpg',
    productCount: 4,
  },
  {
    slug: 'oils',
    name: 'Oils',
    description: 'Pure essential oils and nourishing botanical body blends.',
    image: '/images/categories/oils.jpg',
    productCount: 4,
  },
  {
    slug: 'crafts',
    name: 'Crafts',
    description: 'Unique artisan crafts made from sustainable natural materials.',
    image: '/images/categories/crafts.jpg',
    productCount: 4,
  },
  {
    slug: 'bamboo',
    name: 'Bamboo',
    description: 'Eco-friendly bamboo essentials for sustainable living.',
    image: '/images/categories/bamboo.jpg',
    productCount: 4,
  },
  {
    slug: 'gift-sets',
    name: 'Gift Sets',
    description: 'Curated collections perfect for any special occasion.',
    image: '/images/categories/gift-sets.jpg',
    productCount: 4,
  },
];

const SEED_CRAFTS = [
  {
    id: 'cv-1',
    title: 'Hand-Pouring Soy Candles',
    description: 'Watch the mesmerizing process of melting, mixing scents, and hand-pouring our signature soy candles.',
    videoUrl: '/videos/crafts/cv-1.mp4',
    posterUrl: '/images/crafts/cv-1-poster.jpg',
    artisan: 'Elena Woods',
    category: 'candles',
    duration: '1:45',
  },
  {
    id: 'cv-2',
    title: 'Cold Process Soap Making',
    description: 'Experience the traditional cold process method of crafting luxurious, botanical-infused artisan soaps.',
    videoUrl: '/videos/crafts/cv-2.mp4',
    posterUrl: '/images/crafts/cv-2-poster.jpg',
    artisan: 'Marcus Chen',
    category: 'soaps',
    duration: '2:15',
  },
  {
    id: 'cv-3',
    title: 'Extracting Essential Oils',
    description: 'A behind-the-scenes look at the steam distillation process used to create our pure botanical essential oils.',
    videoUrl: '/videos/crafts/cv-3.mp4',
    posterUrl: '/images/crafts/cv-3-poster.jpg',
    artisan: 'Sarah Jenkins',
    category: 'oils',
    duration: '1:20',
  },
  {
    id: 'cv-4',
    title: 'Carving Sustainable Wood',
    description: 'See the careful techniques used to transform reclaimed walnut wood into beautiful, functional decor pieces.',
    videoUrl: '/videos/crafts/cv-4.mp4',
    posterUrl: '/images/crafts/cv-4-poster.jpg',
    artisan: 'David Miller',
    category: 'crafts',
    duration: '3:10',
  },
  {
    id: 'cv-5',
    title: 'Weaving Natural Seagrass',
    description: 'Follow the rhythmic and intricate patterns of traditional seagrass weaving for our artisan baskets.',
    videoUrl: '/videos/crafts/cv-5.mp4',
    posterUrl: '/images/crafts/cv-5-poster.jpg',
    artisan: 'Amara Diallo',
    category: 'crafts',
    duration: '1:55',
  },
  {
    id: 'cv-6',
    title: 'Bamboo Shaping Techniques',
    description: 'Discover how raw bamboo is sustainably harvested, treated, and shaped into smooth, durable everyday items.',
    videoUrl: '/videos/crafts/cv-6.mp4',
    posterUrl: '/images/crafts/cv-6-poster.jpg',
    artisan: 'Kenji Sato',
    category: 'bamboo',
    duration: '2:30',
  },
  {
    id: 'cv-7',
    title: 'Blending Aromatherapy Oils',
    description: 'Learn about the delicate art of balancing top, middle, and base notes in our signature massage oil blends.',
    videoUrl: '/videos/crafts/cv-7.mp4',
    posterUrl: '/images/crafts/cv-7-poster.jpg',
    artisan: 'Sarah Jenkins',
    category: 'oils',
    duration: '1:15',
  },
  {
    id: 'cv-8',
    title: 'Curating the Perfect Gift Set',
    description: 'The thoughtful process of selecting complementary items and arranging our beautiful wooden gift boxes.',
    videoUrl: '/videos/crafts/cv-8.mp4',
    posterUrl: '/images/crafts/cv-8-poster.jpg',
    artisan: 'Elena Woods',
    category: 'gift-sets',
    duration: '0:45',
  },
];

const SEED_PRODUCTS = [
  // Candles
  {
    slug: 'lavender-dreams-soy-candle',
    name: 'Lavender Dreams Soy Candle',
    category: 'candles',
    description: 'Hand-poured 100% natural soy wax candle infused with pure French lavender essential oil. Features a natural cotton wick that burns cleanly for up to 45 hours.',
    shortDescription: 'Calming French lavender in a clean-burning soy wax candle.',
    price: 24.0,
    compareAtPrice: 28.0,
    images: ['/images/products/lavender-dreams-soy-candle.jpg'],
    rating: 4.8,
    reviewCount: 124,
    stock: 35,
    ingredients: ['100% Natural Soy Wax', 'French Lavender Essential Oil', 'Cotton Wick'],
    featured: true,
    bestSeller: true,
    tags: ['calming', 'lavender', 'aromatherapy', 'soy'],
  },
  {
    slug: 'amber-moss-beeswax-candle',
    name: 'Amber & Moss Beeswax Candle',
    category: 'candles',
    description: 'Warm, earthy notes of amber, oakmoss, and sage in a pure local beeswax base. Naturally purifies the air as it burns with a subtle honey aroma.',
    shortDescription: 'Earthy amber and oakmoss with air-purifying local beeswax.',
    price: 32.0,
    images: ['/images/products/amber-moss-beeswax-candle.jpg'],
    rating: 4.9,
    reviewCount: 88,
    stock: 20,
    materials: ['Local Beeswax', 'Natural Fragrance Oils', 'Wood Wick'],
    featured: false,
    bestSeller: true,
    tags: ['earthy', 'beeswax', 'warm', 'cozy'],
  },
  {
    slug: 'cedarwood-vanilla-candle',
    name: 'Cedarwood & Vanilla Candle',
    category: 'candles',
    description: 'Rich cedarwood paired with creamy Madagascar vanilla creates an inviting, balanced scent. Poured into an amber glass vessel with a wooden crackling wick.',
    shortDescription: 'Rich cedarwood and Madagascar vanilla with a crackling wick.',
    price: 26.0,
    compareAtPrice: 30.0,
    images: ['/images/products/cedarwood-vanilla-candle.jpg'],
    rating: 4.6,
    reviewCount: 65,
    stock: 15,
    ingredients: ['Coconut Soy Wax', 'Cedarwood Essential Oil', 'Vanilla Extract'],
    featured: false,
    bestSeller: false,
    tags: ['woodsy', 'vanilla', 'crackling wick'],
  },
  {
    slug: 'wild-citrus-blossom-candle',
    name: 'Wild Citrus Blossom Candle',
    category: 'candles',
    description: 'Bright and uplifting notes of sweet orange, grapefruit, and neroli blossoms. Perfect for energizing mornings and brightening creative spaces.',
    shortDescription: 'Energizing sweet orange, grapefruit, and neroli blossom.',
    price: 22.0,
    images: ['/images/products/wild-citrus-blossom-candle.jpg'],
    rating: 4.7,
    reviewCount: 42,
    stock: 28,
    ingredients: ['Soy Wax', 'Orange Essential Oil', 'Grapefruit Essential Oil', 'Neroli'],
    featured: true,
    bestSeller: false,
    tags: ['citrus', 'uplifting', 'fresh'],
  },
  // Soaps
  {
    slug: 'wild-honey-oat-soap',
    name: 'Wild Honey & Oat Soap',
    category: 'soaps',
    description: 'Gentle exfoliating bar crafted with raw wildflower honey and finely ground colloidal oats. Deeply moisturizes while calming sensitive skin.',
    shortDescription: 'Raw honey and soothing colloidal oats for sensitive skin.',
    price: 12.0,
    images: ['/images/products/wild-honey-oat-soap.jpg'],
    rating: 4.9,
    reviewCount: 210,
    stock: 50,
    ingredients: ['Saponified Olive Oil', 'Coconut Oil', 'Raw Honey', 'Colloidal Oats', 'Shea Butter'],
    featured: true,
    bestSeller: true,
    tags: ['sensitive skin', 'exfoliating', 'unscented', 'honey'],
  },
  {
    slug: 'activated-charcoal-tea-tree-soap',
    name: 'Activated Charcoal & Tea Tree Soap',
    category: 'soaps',
    description: 'Purifying cold-process soap with activated bamboo charcoal and organic Australian tea tree oil. Draws out impurities and balances oily or acne-prone skin.',
    shortDescription: 'Detoxifying charcoal and tea tree for clear, balanced skin.',
    price: 14.0,
    compareAtPrice: 16.0,
    images: ['/images/products/activated-charcoal-tea-tree-soap.jpg'],
    rating: 4.7,
    reviewCount: 145,
    stock: 40,
    ingredients: ['Bamboo Charcoal', 'Tea Tree Oil', 'Olive Oil', 'Castor Oil'],
    featured: false,
    bestSeller: true,
    tags: ['detox', 'tea tree', 'charcoal', 'cleansing'],
  },
  {
    slug: 'rosemary-mint-swirl-soap',
    name: 'Rosemary Mint Swirl Soap',
    category: 'soaps',
    description: 'Invigorating herbal soap combining crushed garden rosemary with refreshing peppermint. Colored naturally with spirulina and French green clay.',
    shortDescription: 'Invigorating garden rosemary and crisp peppermint bar.',
    price: 13.0,
    images: ['/images/products/rosemary-mint-swirl-soap.jpg'],
    rating: 4.5,
    reviewCount: 52,
    stock: 22,
    ingredients: ['Rosemary Oil', 'Peppermint Oil', 'French Green Clay', 'Coconut Oil'],
    featured: false,
    bestSeller: false,
    tags: ['herbal', 'refreshing', 'clay'],
  },
  {
    slug: 'calendula-chamomile-bar',
    name: 'Calendula & Chamomile Bar',
    category: 'soaps',
    description: 'Ultra-gentle baby and sensitive skin soap infused with whole calendula petals and German chamomile tea. Completely fragrance and dye free.',
    shortDescription: 'Whole calendula petals and chamomile for the gentlest cleanse.',
    price: 15.0,
    images: ['/images/products/calendula-chamomile-bar.jpg'],
    rating: 4.8,
    reviewCount: 78,
    stock: 18,
    ingredients: ['Calendula Infused Olive Oil', 'Chamomile Tea', 'Cocoa Butter'],
    featured: false,
    bestSeller: false,
    tags: ['gentle', 'baby', 'fragrance free'],
  },
  // Oils
  {
    slug: 'pure-eucalyptus-essential-oil',
    name: 'Pure Eucalyptus Essential Oil',
    category: 'oils',
    description: '100% steam-distilled blue mallee eucalyptus oil. Excellent for respiratory clarity, sauna sessions, or diffusing to purify room air.',
    shortDescription: '100% pure steam-distilled Australian eucalyptus oil.',
    price: 18.0,
    images: ['/images/products/pure-eucalyptus-essential-oil.jpg'],
    rating: 4.8,
    reviewCount: 95,
    stock: 30,
    ingredients: ['100% Pure Eucalyptus Globulus Leaf Oil'],
    featured: true,
    bestSeller: false,
    tags: ['essential oil', 'diffuser', 'respiratory', 'pure'],
  },
  {
    slug: 'golden-jojoba-rosehip-facial-oil',
    name: 'Golden Jojoba & Rosehip Facial Oil',
    category: 'oils',
    description: 'Lightweight, fast-absorbing botanical nectar rich in vitamins A and C. Balances sebum production and restores youthful glow without clogging pores.',
    shortDescription: 'Cold-pressed organic jojoba and rosehip seed facial nectar.',
    price: 38.0,
    compareAtPrice: 44.0,
    images: ['/images/products/golden-jojoba-rosehip-facial-oil.jpg'],
    rating: 4.9,
    reviewCount: 160,
    stock: 25,
    ingredients: ['Cold-Pressed Jojoba Oil', 'Organic Rosehip Seed Oil', 'Vitamin E'],
    featured: true,
    bestSeller: true,
    tags: ['skincare', 'glow', 'facial oil', 'anti-aging'],
  },
  {
    slug: 'sweet-almond-body-massage-oil',
    name: 'Sweet Almond Body Massage Oil',
    category: 'oils',
    description: 'Silky smooth expeller-pressed sweet almond oil enriched with calming Roman chamomile and ylang-ylang. Glides effortlessly for soothing home massage.',
    shortDescription: 'Silky sweet almond oil with chamomile and ylang-ylang.',
    price: 28.0,
    images: ['/images/products/sweet-almond-body-massage-oil.jpg'],
    rating: 4.6,
    reviewCount: 44,
    stock: 19,
    ingredients: ['Sweet Almond Oil', 'Roman Chamomile Oil', 'Ylang Ylang Oil'],
    featured: false,
    bestSeller: false,
    tags: ['massage', 'body', 'hydrating'],
  },
  {
    slug: 'organic-argan-hair-serum',
    name: 'Organic Moroccan Argan Hair Serum',
    category: 'oils',
    description: 'Cold-pressed authentic Moroccan argan oil blended with rosemary and cedarwood to tame frizz, mend split ends, and promote scalp health.',
    shortDescription: 'Pure Moroccan argan oil for silky, frizz-free hair.',
    price: 34.0,
    images: ['/images/products/organic-argan-hair-serum.jpg'],
    rating: 4.7,
    reviewCount: 68,
    stock: 14,
    ingredients: ['100% Pure Argania Spinosa Kernel Oil', 'Rosemary Leaf Extract'],
    featured: false,
    bestSeller: false,
    tags: ['hair care', 'argan', 'moroccan', 'frizz'],
  },
  // Crafts
  {
    slug: 'hand-carved-walnut-serving-board',
    name: 'Hand-Carved Walnut Serving Board',
    category: 'crafts',
    description: 'Artisan charcuterie board sculpted from single-slab reclaimed American black walnut. Finished with organic food-grade beeswax and mineral oil.',
    shortDescription: 'Single-slab reclaimed black walnut artisan serving board.',
    price: 65.0,
    compareAtPrice: 75.0,
    images: ['/images/products/hand-carved-walnut-serving-board.jpg'],
    rating: 5.0,
    reviewCount: 38,
    stock: 8,
    materials: ['American Black Walnut', 'Food-Grade Beeswax Polish'],
    featured: true,
    bestSeller: true,
    tags: ['woodwork', 'kitchen', 'artisan', 'charcuterie'],
  },
  {
    slug: 'woven-seagrass-storage-basket',
    name: 'Woven Seagrass Storage Basket',
    category: 'crafts',
    description: 'Traditional coil-woven basket crafted from sustainably harvested wild seagrass. Features sturdy integrated handles for blankets, plants, or towels.',
    shortDescription: 'Hand-woven wild seagrass basket with integrated handles.',
    price: 42.0,
    images: ['/images/products/woven-seagrass-storage-basket.jpg'],
    rating: 4.8,
    reviewCount: 56,
    stock: 16,
    materials: ['Natural Seagrass', 'Jute Cord'],
    featured: false,
    bestSeller: false,
    tags: ['home decor', 'basket', 'sustainable', 'storage'],
  },
  {
    slug: 'hand-thrown-ceramic-match-striker',
    name: 'Hand-Thrown Ceramic Match Striker',
    category: 'crafts',
    description: 'Wheel-thrown stoneware match holder with a textured unglazed strike surface. Includes 50 strike-anywhere matches to elevate your candle rituals.',
    shortDescription: 'Stoneware pottery match striker with strike-anywhere surface.',
    price: 24.0,
    images: ['/images/products/hand-thrown-ceramic-match-striker.jpg'],
    rating: 4.6,
    reviewCount: 29,
    stock: 22,
    materials: ['Speckled Stoneware Clay', 'Matte Glaze'],
    featured: false,
    bestSeller: false,
    tags: ['pottery', 'ceramics', 'candle accessories'],
  },
  {
    slug: 'linen-waffle-hand-towel-set',
    name: 'Pure Linen Waffle Hand Towel Set',
    category: 'crafts',
    description: 'Set of two generously sized waffle-weave towels loomed from 100% European flax. Naturally antimicrobial, highly absorbent, and softens with every wash.',
    shortDescription: 'Pair of waffle-woven European linen hand towels.',
    price: 36.0,
    images: ['/images/products/linen-waffle-hand-towel-set.jpg'],
    rating: 4.9,
    reviewCount: 71,
    stock: 19,
    materials: ['100% European Flax Linen'],
    featured: false,
    bestSeller: true,
    tags: ['textiles', 'linen', 'bathroom', 'kitchen'],
  },
  // Bamboo
  {
    slug: 'organic-bamboo-cutlery-travel-kit',
    name: 'Organic Bamboo Cutlery Travel Kit',
    category: 'bamboo',
    description: 'Zero-waste travel set featuring a knife, fork, spoon, chopsticks, and straw inside a compact organic canvas rollup pouch.',
    shortDescription: 'Zero-waste reusable bamboo cutlery in a washable canvas pouch.',
    price: 16.0,
    images: ['/images/products/organic-bamboo-cutlery-travel-kit.jpg'],
    rating: 4.7,
    reviewCount: 112,
    stock: 45,
    materials: ['Moso Bamboo', 'Organic Cotton Canvas'],
    featured: false,
    bestSeller: true,
    tags: ['zero waste', 'travel', 'bamboo', 'sustainable'],
  },
  {
    slug: 'bamboo-soap-dish-drainer',
    name: 'Slotted Bamboo Soap Dish',
    category: 'bamboo',
    description: 'Self-draining natural bamboo tray that elevates artisanal soaps, allowing air to circulate so bars stay firm and last significantly longer.',
    shortDescription: 'Self-draining bamboo tray to extend the life of handmade soaps.',
    price: 9.0,
    compareAtPrice: 12.0,
    images: ['/images/products/bamboo-soap-dish-drainer.jpg'],
    rating: 4.8,
    reviewCount: 184,
    stock: 60,
    materials: ['Water-Resistant Treated Bamboo'],
    featured: false,
    bestSeller: false,
    tags: ['soap dish', 'bathroom', 'eco friendly'],
  },
  {
    slug: 'bamboo-fiber-kitchen-cloths',
    name: 'Bamboo Fiber Kitchen Cleaning Cloths',
    category: 'bamboo',
    description: 'Pack of 4 super-absorbent dishcloths spun from natural bamboo cellulose. Naturally resists odors and cleans counters effortlessly without lint.',
    shortDescription: 'Pack of 4 odor-resistant, ultra-absorbent bamboo dishcloths.',
    price: 15.0,
    images: ['/images/products/bamboo-fiber-kitchen-cloths.jpg'],
    rating: 4.5,
    reviewCount: 39,
    stock: 35,
    materials: ['100% Bamboo Viscose Fiber'],
    featured: false,
    bestSeller: false,
    tags: ['cleaning', 'kitchen', 'plastic free'],
  },
  {
    slug: 'bamboo-bath-caddy-bridge',
    name: 'Extendable Bamboo Bath Caddy Bridge',
    category: 'bamboo',
    description: 'Water-resistant bath bridge that expands to fit standard tubs. Equipped with book/tablet rest, wine glass slot, and space for your candle and soap.',
    shortDescription: 'Luxury expandable bamboo bathtub tray for relaxation rituals.',
    price: 48.0,
    images: ['/images/products/bamboo-bath-caddy-bridge.jpg'],
    rating: 4.9,
    reviewCount: 61,
    stock: 12,
    materials: ['Natural Solid Bamboo', 'Waterproof Varnish'],
    featured: true,
    bestSeller: false,
    tags: ['bath', 'relaxation', 'luxury', 'caddy'],
  },
  // Gift Sets
  {
    slug: 'the-artisan-candle-trio',
    name: 'The Artisan Candle Trio',
    category: 'gift-sets',
    description: 'Curated 3-piece sampler of our most beloved soy candles: Lavender Dreams, Amber & Moss, and Wild Citrus. Beautifully gift-boxed in recycled paper.',
    shortDescription: '3-piece handcrafted soy candle set in recycled gift packaging.',
    price: 58.0,
    compareAtPrice: 68.0,
    images: ['/images/products/the-artisan-candle-trio.jpg'],
    rating: 4.9,
    reviewCount: 82,
    stock: 20,
    featured: true,
    bestSeller: true,
    tags: ['gift set', 'candles', 'trio', 'present'],
  },
  {
    slug: 'botanical-bath-sanctuary-box',
    name: 'Botanical Bath Sanctuary Box',
    category: 'gift-sets',
    description: 'Complete home spa experience: Wild Honey Oat Soap, Sweet Almond Massage Oil, Eucalyptus Oil, and a slotted bamboo drainer in an artisan wooden keepsake box.',
    shortDescription: 'Complete natural bath ritual set in a wooden keepsake box.',
    price: 68.0,
    images: ['/images/products/botanical-bath-sanctuary-box.jpg'],
    rating: 5.0,
    reviewCount: 47,
    stock: 15,
    featured: true,
    bestSeller: false,
    tags: ['spa', 'pamper', 'gift box', 'ritual'],
  },
  {
    slug: 'pure-essential-wellness-bundle',
    name: 'Essential Wellness Aromatherapy Bundle',
    category: 'gift-sets',
    description: 'Set of 4 essential oils (Eucalyptus, Lavender, Sweet Orange, Tea Tree) with an artisan ceramic aroma stone diffuser.',
    shortDescription: '4 essential oils accompanied by a ceramic aroma diffuser stone.',
    price: 52.0,
    compareAtPrice: 60.0,
    images: ['/images/products/pure-essential-wellness-bundle.jpg'],
    rating: 4.7,
    reviewCount: 31,
    stock: 18,
    featured: false,
    bestSeller: false,
    tags: ['aromatherapy', 'wellness', 'bundle'],
  },
  {
    slug: 'eco-friendly-starter-collection',
    name: 'Sustainable Living Starter Collection',
    category: 'gift-sets',
    description: 'Thoughtful bundle including bamboo travel cutlery, 2 linen waffle towels, wild honey soap, and a natural bamboo soap caddy.',
    shortDescription: 'Essential sustainable living kit in an eco-friendly gift pack.',
    price: 46.0,
    images: ['/images/products/eco-friendly-starter-collection.jpg'],
    rating: 4.8,
    reviewCount: 54,
    stock: 22,
    featured: false,
    bestSeller: false,
    tags: ['starter kit', 'zero waste', 'sustainable gift'],
  },
];

async function seed() {
  console.log('[Seed] Connecting to MongoDB...');
  await connectDB();

  console.log('[Seed] Clearing existing collections...');
  await Promise.all([
    Category.deleteMany({}),
    Product.deleteMany({}),
    CraftVideo.deleteMany({}),
  ]);

  console.log('[Seed] Seeding categories...');
  await Category.insertMany(SEED_CATEGORIES);

  console.log('[Seed] Seeding craft videos...');
  await CraftVideo.insertMany(SEED_CRAFTS);

  console.log('[Seed] Seeding products...');
  await Product.insertMany(SEED_PRODUCTS);

  console.log(`[Seed] Successfully seeded:`);
  console.log(` - ${SEED_CATEGORIES.length} Categories`);
  console.log(` - ${SEED_PRODUCTS.length} Products`);
  console.log(` - ${SEED_CRAFTS.length} Craft Videos`);

  await mongoose.disconnect();
  console.log('[Seed] Finished and disconnected.');
  process.exit(0);
}

seed().catch(err => {
  console.error('[Seed Error]:', err);
  process.exit(1);
});
